quote_site/quote_site/urls.py
# quote_site/urls.py
from django.contrib import admin
from django.urls import path, include
from quotes import views


urlpatterns = [
    path("", include("quotes.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    # path('accounts/', include('sjango.contrib.auth.urls')),
]

quote_site/quotes/urls.py
#tamplates/urls.py
from django.urls import path, include
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.home, name="home"), # quotes:home
 
    path("add_author", views.add_author, name="add_author"), 
    path("add_tag", views.add_tag, name="add_tag"), 
    path("add_quote", views.add_quote, name="add_quote"),
    path('author/<int:pk>/', views.author_detail, name='author_detail'),
    path('tag/<int:tag_id>/', views.tag_detail, name='tag_detail'),
    
]

quote_site/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'), 
    # path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quote_site/quotes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Author(models.Model):
    fullname = models.CharField(max_length=200)
    born_date = models.DateField()
    born_location = models.CharField(max_length=1502, default='Default Location')
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.fullname
    

class Tag(models.Model):
    name = models.CharField(max_length=120, null=False, unique=True)

    def __str__(self):
        return self.name
    

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        default=None,
        null=True,
    )

    def __str__(self):
        return self.text

quote_site/quotes/forms.py
from django.forms import ModelForm, CharField,TextInput, DateField, DateInput, ModelChoiceField, Select, Textarea, ModelMultipleChoiceField, SelectMultiple
from .models import Author, Quote, Tag


class QuoteForm(ModelForm):
    quote = CharField(widget=Textarea(attrs={"class": "form-control", "rows": "5"}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), widget=Select(attrs={"class": "form-select"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by("name"),widget=SelectMultiple(attrs={"size": "12",}))

    class Meta:
        model = Quote
        fields = ['author', 'quote', 'tags', ]

class TagForm(ModelForm):
    name = CharField(max_length=30, min_length=2, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name', ]

class AuthorForm(ModelForm):
    fullname = CharField(max_length=40, min_length=2, widget=TextInput(attrs={"class": "form-control"}))
    born_date  = DateField(widget=DateInput(attrs={"class": "form-control"}))  #birth_date
    born_location = CharField(max_length=150,widget=TextInput(attrs={"class": "form-control",}),)
    description = CharField(max_length=40, min_length=30, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date',"born_location", 'description',  ]

quote_site/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Author, Quote, Tag
from .forms import AuthorForm, QuoteForm, TagForm
from django.core.paginator import Paginator
from django.db.models import Count

def home(request):
    quotes = Quote.objects.all()
    return render(request, 'quotes/home.html', {'quotes': quotes})

# def author(request, author_name):
#     author = Author.objects.get(name=author_name)
#     if not author:
#         author = None

#     return render(request, "quotes/author_detail.html", context={"author": author})

def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'quotes/author_detail.html', {'author': author})

def tag(request, tag_name):
    quotes = Quote.objects.filter(tags__name=tag_name).order_by("-created_at")
    top_tags = Tag.objects.annotate(tag_count=Count("quote")).order_by("-tag_count")[
        :10
    ]
    return render(
        request,
        "quotes/tag_view.html",
        context={
            "top_tags": top_tags,
            "tag_name": tag_name,
            "quotes": quotes,
        },
    )

def tag_detail(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    quotes = tag.quote_set.all()
    return render(request, 'quotes/tag_detail.html', {'tag': tag, 'quotes': quotes})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = QuoteForm()

    return render(request, 'quotes/add_quote.html', {'form': form})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = AuthorForm()
        
    return render(request, 'quotes/add_author.html', {'form': form})

@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = TagForm()
        
    return render(request, 'quotes/add_tag.html', {'form': form})

quote_site/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'quotes:add_author' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label>Enter the author fullname:</label>
                {{form.fullname}}        
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div style="padding: 10px">
            <label>Enter the author born date:</label>
                {{form.born_date}}
            <span>{{ form.errors.born_date }}</span>
        </div>
        <div style="padding: 10px">
            <label>Enter the author born location:</label>
                {{form.born_location}}
            <span>{{ form.errors.born_location }}</span>
        </div>
        <div style="padding: 10px">
            <label>Enter the author biografia:</label>
                {{form.description}}
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% endblock %}

quote_site/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote text:</label>
            {{form.quote}}        
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author fullname:</label>
            {{form.author}}
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label>Select the tag:</label>
            {{form.tags}}
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quote_site/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'quotes:add_tag' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label>Enter the tag name:</label>
                {{form.name}}        
            <span>{{ form.errors.name }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% endblock %}

quote_site/quotes/templates/quotes/author_detail.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="container mt-3">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ author.fullname }}</h5>
            <p class="card-text">{{ quote.text }}</p>
            <p class="card-text"><small class="text-muted">Author's Birth Date: {{ author.born_date }}</small></p>
            <p class="card-text"><small class="text-muted">Author's Bio: {{ author.description }}</small></p>
            <p class="card-text"><small class="text-muted">Author's Born Location: {{ author.born_location }}</small></p>
        </div>
    </div>
</div>

{% endblock %}

quote_site/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" 
                integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
        crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link btn btn-outline-primary" aria-current="page" href="{% url 'quotes:home' %}">Home</a>
              {% if user.is_authenticated %}
              <a class="nav-link btn btn-success" href="{% url 'quotes:add_quote' %}">Add Quote</a>
              <a class="nav-link btn btn-info" href="{% url 'quotes:add_author' %}">Add Author</a>
              <a class="nav-link btn btn-warning" href="{% url 'quotes:add_tag' %}">Add Tag</a>
              <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Logout</button>
              </form>
              {% else %}
              <a class="nav-link btn btn-warning" href="{% url 'users:login' %}">Log in</a>
              <a class="nav-link btn btn-warning" href="{% url 'users:signup' %}">Sign up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    <header>
        <!-- Header content goes here -->
    </header>
    <main>
        {% block content %}
        <!-- Main content goes here -->
        {% endblock %}
        
    </main>
    <footer>
        <!-- Footer content goes here -->
    </footer>
</body>
</html>

quote_site/quotes/templates/quotes/home.html
{% extends "quotes/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container mt-3">
    <h2>Quotes of great people</h2>
</div>

    <div class="container mt-3">
        {% for quote in quotes %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title quote-text">"{{ quote.quote }}"</h5>
                    <h6 class="author_stile">Author: <a href="{% url 'quotes:author_detail' quote.author.pk %}">{{ quote.author.fullname }}</a></h6>
                    <p class="card-text">Tags: 
                        {% for tag in quote.tags.all %}
                            <a href="{% url 'quotes:tag_detail' tag.pk %}">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

quote_site/quotes/templates/quotes/tag_detail.html
{% extends "quotes/base.html" %}

{% block title %}{{ tag.name }}{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1>{{ tag.name }}</h1>
        <h2>Quotes with this tag:</h2>
        {% for quote in quotes %}
            <h3>"{{ quote.quote }}"</h3>
            <p>Author: <a href="{% url 'quotes:author_detail' quote.author.pk %}">{{ quote.author.fullname }}</a></p>
        {% endfor %}
    </div>
{% endblock %}